### ISSUE TITLE
Mob cannon no longer capturing zombie villagers

### ISSUE THREAD

**Issue by TeamOah** [Slimefun-Addon-Community/MobCapturer#44]
### Checklist

- [X] You are using official version downloaded from Blob Builds (https://blob.build)
- [X] You did not modify the jar file
- [X] You searched existing issues, and could not find any existing bug report on this

### Description

MobCapturer cannon is not getting zombie villagers.
Works ok with other mobs that it can capture.

### Reproduction Steps

1 get a mob cannon and the pellet.
2 try to capture a zombie villager.

### Expected Behavior

It should capture a zombie villager and it does look like it's shooting the pellet properly, it should catch one.

### Server Software

Paper

### Minecraft Version

1.20.4

### Slimefun version

dev 1157

### Plugin version

vDEV 35

**Comment by TeamOah** [comment]
Got a server log from a friend who also experiences it on his server.
[06:35:18] [Server thread/ERROR]: Could not pass event ProjectileHitEvent to MobCapturer vDev - 35
java.lang.IncompatibleClassChangeError: Found class org.bukkit.entity.Villager$Profession, but interface was expected
	at MobCapturer.jar/io.github.thebusybiscuit.mobcapturer.adapters.mobs.ZombieVillagerAdapter.saveData(ZombieVillagerAdapter.java:40) ~[MobCapturer.jar:?]
	at MobCapturer.jar/io.github.thebusybiscuit.mobcapturer.adapters.mobs.ZombieVillagerAdapter.saveData(ZombieVillagerAdapter.java:19) ~[MobCapturer.jar:?]
	at MobCapturer.jar/io.github.thebusybiscuit.mobcapturer.items.MobEgg.getEggItem(MobEgg.java:60) ~[MobCapturer.jar:?]
	at MobCapturer.jar/io.github.thebusybiscuit.mobcapturer.listeners.PelletListener.capture(PelletListener.java:92) ~[MobCapturer.jar:?]
	at MobCapturer.jar/io.github.thebusybiscuit.mobcapturer.listeners.PelletListener.onProjectileHit(PelletListener.java:51) ~[MobCapturer.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor217.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-150-e61b73f]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:1497) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
	at net.minecraft.world.entity.projectile.Projectile.preHitTargetOrDeflectSelf(Projectile.java:202) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
	at net.minecraft.world.entity.projectile.ThrowableProjectile.tick(ThrowableProjectile.java:69) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1415) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1301) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
	at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:922) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:902) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1779) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by DeltaR4v0x** [comment]
I have the same problem with the same version. I feel like it's the profession that isn't working properly

**Comment by ybw0014** [comment]
Fixed with [976de0e](https://github.com/Slimefun-Addon-Community/MobCapturer/commit/976de0e9dbb9ffce16bd1c8f3d8d64e42fe2ce2d)
